version: '3'
services:
  web:
    build: .
    ports:
      - "5006:5000"
    volumes:
      - ./:/app
    networks:
      default:
        ipv4_address: 172.18.2.194
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.2.192/29
          gateway: 172.18.2.193
