version: '3'
services:
  web:
    build: .
    ports:
      - "5006:5000"
    volumes:
      - ./:/app
    depends_on:
      - redis
    networks:
      default:
        ipv4_address: 172.18.2.194

  redis:
    image: "redis:alpine"
    volumes:
      - ./redis/data:/data
      - ./redis:/usr/local/etc/redis
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      default:
        ipv4_address: 172.18.2.195
networks:
  default:
    ipam:
      config:
        - subnet: 172.18.2.192/29
          gateway: 172.18.2.193
